server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.11.128
    username: leyou
    password: leyou
    virtual-host: leyou
leyou:
  sms:
    accessKeyId: LTAI4FskspNW8VPWPypEHaMg # 你自己的accessKeyId
    accessKeySecret: SSHZpISoai8OBLx9OcVAQYo0uMOYZp # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_180357186 # 模板名称